### ISSUE TITLE
Boot crash pls help

### ISSUE THREAD

**Issue by SeanChengN** [hlysine/create_power_loader#1]
forge: 1.20.1-47.1.3
create: 1.20.1-0.5.1.f
create_power_loader-1.1.0-mc1.20.1
log: [crash-2023-11-13_09.42.32-fml.txt](https://github.com/hlysine/create_power_loader/files/13330083/crash-2023-11-13_09.42.32-fml.txt)

**Comment by hlysine** [comment]
[UNZIP ME create_power_loader-1.1.0-dev-mc1.20.1.zip](https://github.com/hlysine/create_power_loader/files/13335335/UNZIP.ME.create_power_loader-1.1.0-dev-mc1.20.1.zip)

Can you test if this version fixes your issue?

**Comment by SeanChengN** [comment]
> [UNZIP ME create_power_loader-1.1.0-dev-mc1.20.1.zip](https://github.com/hlysine/create_power_loader/files/13335335/UNZIP.ME.create_power_loader-1.1.0-dev-mc1.20.1.zip)
> 
> Can you test if this version fixes your issue?

Works well! Thanks for your quick reply!
