### ISSUE TITLE
Fabric 1.20.1 chunks not loading properly

### ISSUE THREAD

**Issue by 3dEADto2** [hlysine/create_power_loader#12]
![2024-02-26_08 47 44](https://github.com/hlysine/create_power_loader/assets/110291809/f37fbd1a-6afb-422b-90cd-679b164b9159)
![2024-02-26_09 10 35](https://github.com/hlysine/create_power_loader/assets/110291809/0c39f626-7445-4264-85c8-7d15c537e185)
With two setups as shown in the picture above, the chunk loaders in other dimensions do not work properly. (The overworld setup also has a chunk loader, it just isn't shown in the picture). With "power loader" enabled, only the chunk loaders in the dimension in which the player is located, both the redstone and the create contraption work. In the dimension in which there is no player, only the redstone works but no longer the create contraption. Even if I load the chunks manually via /forceload the problem persists. Only when I disable "power loader" and then load the chunks via /forceload (or e.g. the mod "chunk loaders") do both redstone and the create contraption work without problems in all dimensions. It could also be that it's because of my modpack that a mod doesn't play well with "power loaders" (but it does with "chunk loaders"), but I wanted to let you know anyway. (By the way, I use "create fabric sodium fix" instead of the normal "create fabric" if that matters.)

**Comment by hlysine** [comment]
This might be a discrepancy between Forge's native chunk manager and Fabric's implementation provided by PortingLib. Need further investigation to confirm.

**Comment by 3dEADto2** [comment]
Ok, I tested it with a smaller modlist, maybe that will help replicate it. (Even with this modlist the problem persists)
Modlist:
- Create Fabric Fixes 0.0.1+1.20.1-create-0.5.1d
- Create Fabric Sodium Fix 0.5.1-d-build.1161+mc1.20.1
- Create: Power Loader (Fabric) 1.4.1-mc1.20.1-fabric
- Fabric API 0.92.0+1.20.1
- Indium 1.0.30+mc1.20.4
- Just Enough Items 15.3.0.4
- Sodium mc1.20.1-0.5.8
- Fabric Loader Version 0.15.6

**Comment by squimbo** [comment]
can confirm, it sucks :(

**Comment by Hyperbus02** [comment]
Same here, they just dont work at all be it on a train station or powered, simple as that

**Comment by colemy** [comment]
Same here, the mod just does not work in fabric 1.20.1. Impossible to chunk load my 1 chunk nether lava farm with train travelling back and forth in the portal. The train goes into the nether and never comes back unless I go through the portal myself...

**Comment by Hyperbus02** [comment]
> Same here, the mod just does not work in fabric 1.20.1. Impossible to chunk load my 1 chunk nether lava farm with train travelling back and forth in the portal. The train goes into the nether and never comes back unless I go through the portal myself...

This is my exact scenario. I tried havin a brass loader on the stations as well as one being rotated together and still nothing.

**Comment by hlysine** [comment]
Good news, I have identified the problem to be a bug in Porting Lib. I'll submit a fix and update Power Loader later
