### ISSUE TITLE
Fabric Version uses Forge Create, not Fabric Create in Modrinth

### ISSUE THREAD

**Issue by pauliesnug** [hlysine/create_power_loader#13]
Hiya~
In the Modrinth page for Create: Power Loader for Fabric, the dependency is marked as the regular `create` modrinth page, instead of the Create Fabric modrinth page.

See [this page](https://modrinth.com/mod/create-power-loader-fabric/version/1.4.2-mc1.20.1-fabric), the dependency is marked as https://modrinth.com/mod/create, rather than https://modrinth.com/mod/create-fabric

**Comment by hlysine** [comment]
Fixed. Thanks for the report
