### ISSUE TITLE
Fabric : Crafting recipe not working

### ISSUE THREAD

**Issue by Alixollo** [hlysine/create_power_loader#17]
It seems the crafting recipe for the brass chunk loader is not working on Fabric. Furthermore, the craft appears incorrectly in JEI, as the glass seems to be missing.

![image](https://github.com/hlysine/create_power_loader/assets/89808322/1a962864-66fd-460c-b812-ac2ba6f56d54)

**Comment by hlysine** [comment]
Please update Power Loader to 1.4.2 and try again. I'm pretty sure this is a tag issue that has been fixed.
