### ISSUE TITLE
incompatible with Create Fabric 0.5.1-f

### ISSUE THREAD

**Issue by Karotte128** [hlysine/create_power_loader#18]
it crashes.

**Comment by hlysine** [comment]
0 5.1f has just come out. It will take time before addons are updated to work with it.

**Comment by pauliesnug** [comment]
> 0 5.1f has just come out. It will take time before addons are updated to work with it.

Is there an estimated timeframe? There only seems to be a few API changes with the creative tab

**Comment by Fauli1221** [comment]
According to the changelog this is fixed can the issue be closed?
https://github.com/hlysine/create_power_loader/blob/fabric/CHANGELOG.md

**Comment by hlysine** [comment]
Ah yes, thanks for the reminder
