### ISSUE TITLE
1.19.2 fabric port?

### ISSUE THREAD

**Issue by Cristiandis** [hlysine/create_power_loader#19]
is it possible to have a port for 1.19.2

**Comment by Jakub-Wilk** [comment]
Is "longer time" on the scale of weeks or months here? No pressure, just curious what the ETA is

**Comment by hlysine** [comment]
To be honest, it would be on a scale of days if I had the time to work on it, but right now it will be at least a month.

**Comment by hlysine** [comment]
Power Loader for fabric 1.19 is out: https://modrinth.com/mod/create-power-loader-fabric
