### ISSUE TITLE
Server wont starting with mod installed

### ISSUE THREAD

**Issue by Y5R** [hlysine/create_power_loader#2]
Cant start server with create power loader mod installed (works fine on client, server starts without create power loader mod installed)

Mod version: create_power_loader-1.2.0-mc1.20.1
Minecraft version: 1.20.1
Forge: 47.1.3

Log file: [latest.log](https://github.com/hlysine/create_power_loader/files/13512328/latest.log)

**Comment by hlysine** [comment]
This is due to JEI not being installed on your server when this mod is trying to register additional recipes. A quick workaround before I fix this is to install JEI on your server.

**Comment by Y5R** [comment]
That worked, thanks!
