### ISSUE TITLE
Unnecessary bundling of porting lib modules

### ISSUE THREAD

**Issue by IThundxr** [hlysine/create_power_loader#23]
`accessors,base,entity,extensions,networking,obj_loader,tags,transfer,models,tool_actions,client_events,brewing` are all provided transitively through create fabric already, you can just replace https://github.com/hlysine/create_power_loader/blob/a3af88d454748ab87bb8ab53c428c06b91ac8ab3/gradle.properties#L24 with `port_lib_modules = chunk_loading` to only bundle what you need. This also makes the jar quite a bit smaller

**Comment by hlysine** [comment]
I see. Thanks for the heads up
