### ISSUE TITLE
Unable to complete server startup

### ISSUE THREAD

**Issue by INV-PLA** [hlysine/create_power_loader#29]
Placing chunkloaded in minecraft:the_end or minecraft:the_nether can cause the Preparing start region for dimension to get stuck
Only for servers

**Comment by hlysine** [comment]
What are your Minecraft, Create and Power Loader versions, and what loader (Forge/Fabric) are you using? Please also send your logs.

**Comment by INV-PLA** [comment]
[2024-07-20-9.log](https://github.com/user-attachments/files/16319360/2024-07-20-9.log)
Forge
Mohist-1.20.1-build792.jar
create_power_loader-1.5.0-mc1.20.1.jar
Deleting 'creat_power_roader-server.toml' seems to start the server
I don't know English, the content is machine translated. Please forgive me

**Comment by INV-PLA** [comment]
> What are your Minecraft, Create and Power Loader versions, and what loader (Forge/Fabric) are you using? Please also send your logs.

[16:25:41 INFO]: Mohist: 1.20.1-792
[16:25:41 INFO]: Forge: 47.3.5
[16:25:41 INFO]: NeoForge: 47.1.105
[16:25:41 INFO]: Bukkit: 997de31d
[16:25:41 INFO]: CraftBukkit: ddc9a2dad
[16:25:41 INFO]: Spigot: d2eba2c8

**Comment by hlysine** [comment]
It might be a config issue due to Power Loader running in Mohist. I don't plan to support Mohist so there's nothing I can do if the mod doesn't run optimally in it.

**Comment by INV-PLA** [comment]
> It might be a config issue due to Power Loader running in Mohist. I don't plan to support Mohist so there's nothing I can do if the mod doesn't run optimally in it.

Is there anything special about deleting the configuration file and the corresponding loader block? I thought this would be enough to load it
