### ISSUE TITLE
Game Breaking Bug on server

### ISSUE THREAD

**Issue by KarmaAvec1C** [hlysine/create_power_loader#31]
On OMGSERV powered Minecraft server, using any number of chunkloaders destroys the game. As soon as someone logs in after any backup, FPS drop to less than 1 and ticks don't run anymore until the server crashes. Happened on 3 separate modpacks each time the day after we started using the chunkloaders, after we went to sleep. Restoring an older backup from before the chunkloaders were placed fixes everything

Using forge 47.2.0 on Minecraft 1.20.1

![image_2024-08-08_154946828](https://github.com/user-attachments/assets/272d43a2-106b-4ee7-8d66-26f352e6e863)

**Comment by hlysine** [comment]
Please post your crash report

**Comment by KarmaAvec1C** [comment]
im not a big user of server and stuff and since i rolled back to before the crashes i dont have anything else than the screenshots

**Comment by hlysine** [comment]
There's nothing I can do without more information.
