### ISSUE TITLE
net.minecraft.nbt.CompoundTag.m_128437_-String.-int-because-nbt-is-null

### ISSUE THREAD

**Issue by Kluha52** [hlysine/create_power_loader#36]
My friends and I encountered this error and we need your help to solve it 
I will attach the logs below to make it more convenient for you
[debug (1).log](https://github.com/user-attachments/files/16946368/debug.1.log)
[latest (5).log](https://github.com/user-attachments/files/16946369/latest.5.log)

**Comment by hlysine** [comment]
Do you have the same version of Create: Power Loader on your server and all your clients? Does this only happen when a train is built or when a train station is placed?

**Comment by Kluha52** [comment]
> Do you have the same version of Create: Power Loader on your server and all your clients? Does this only happen when a train is built or when a train station is placed?

We don’t get a Create power Loader and Train on the our server we don’t know what a problem

**Comment by hlysine** [comment]
This is the issue tracker for Create: Power Loader. If your problem is not related to this mod then there's nothing I can help with.
